apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/minio
    targetRevision: "17.0.19"
    path: .
    helm:
      values: |
        image:
          repository: minio/minio
          tag: latest
        console:
          image:
            repository: public.ecr.aws/bitnami/minio-object-browser
            tag: latest
        global:
          security:
            allowInsecureImages: true
        auth:
          rootUser: minio
          rootPassword: minio123
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
        persistence:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
